enchantments:
  brewing:
    id: 1000 # The ID must not match any other enchantment ID. The default enchantments have an ID between 1 and 100, it is not recommended to use IDs in that range
    enchant_name: '&7Alchemic Fortitude'
    description: '&8> Increases the speed of your brewing by &e50&8-&e75&8-&e100%&8, and quality of your potions by &e20&8-&e35&8-&e50%&8'
    enabled: true
    weight: 40
    max_level: 3
    max_level_table: 3
    trade_cost_base_lower: 32
    trade_cost_base_upper: 16
    trade_cost_lv_lower: 8
    trade_cost_lv_upper: 16
    trade_enabled: true
    book_only: false
    icon: BREWING_STAND
    is_treasure: false
    compatible_with:
      - HELMETS
    stats:
      ALCHEMY_BREW_SPEED:
        base: 0.5
        lv: 0.25
      ALCHEMY_QUALITY_GENERAL:
        base: 20
        lv: 15
  smithing:
    id: 1001
    enchant_name: '&7Forgemaster'
    description: '&8> Improves your smithing skill by &e20&8-&e35&8-&e50'
    enabled: true
    weight: 20
    max_level: 3
    max_level_table: 3
    trade_cost_base_lower: 32
    trade_cost_base_upper: 16
    trade_cost_lv_lower: 8
    trade_cost_lv_upper: 16
    trade_enabled: true
    book_only: false
    icon: ANVIL
    is_treasure: false
    compatible_with: 
      - CHESTPLATES
    stats:
      SMITHING_QUALITY_GENERAL:
        base: 20
        lv: 15
  bleeding:
    id: 1002
    enchant_name: '&7Bloodletting'
    description: '&8> Damage dealt by bleeding is improved by &e1&8-&e1.5&8-&e2&8 points'
    enabled: true
    weight: 40
    max_level: 3
    max_level_table: 3
    trade_cost_base_lower: 32
    trade_cost_base_upper: 16
    trade_cost_lv_lower: 8
    trade_cost_lv_upper: 16
    trade_enabled: true
    book_only: false
    icon: IRON_SWORD
    is_treasure: false
    compatible_with: 
      - SWORDS
      - AXES
    stats:
      BLEED_DAMAGE:
        base: 1
        lv: 0.5
      BLEED_CHANCE:
        base: 0.1
        lv: 0
  reach:
    id: 1003
    enchant_name: '&7Longsword'
    description: '&8> Increases attack reach by &e0.5&8-&e1&8-&e1.5&8 blocks'
    enabled: true
    weight: 20
    max_level: 3
    max_level_table: 3
    trade_cost_base_lower: 32
    trade_cost_base_upper: 16
    trade_cost_lv_lower: 8
    trade_cost_lv_upper: 16
    trade_enabled: true
    book_only: false
    icon: DIAMOND_SWORD
    is_treasure: false
    compatible_with: 
      - SWORDS
    stats:
      ATTACK_REACH_BONUS:
        base: 0.5
        lv: 0.5
  dodge:
    id: 1004
    enchant_name: '&7Swiftfooted'
    description: '&8> Increases dodge chance by &e5&8-&e10&8-&e15%&8'
    enabled: true
    weight: 20
    max_level: 3
    max_level_table: 3
    trade_cost_base_lower: 32
    trade_cost_base_upper: 16
    trade_cost_lv_lower: 8
    trade_cost_lv_upper: 16
    trade_enabled: true
    book_only: false
    icon: LEATHER_BOOTS
    is_treasure: false
    compatible_with: 
      - BOOTS
    stats:
      DODGE_CHANCE:
        base: 0.05
        lv: 0.05
